$font = JetBrainsMono Nerd Font
$font_size = 80
$red = rgb(f38ba8)
$base = rgba(1e1e2ee6)
$rosewater = rgb(f5e0dc)
$muave = rgb(cba6f7)

general {
    hide_cursor = true
    ignore_empty_input = true
    immediate_render = false
    text_trim = true
    fractional_scaling = 2
    screencopy_mode = 0
    fail_timeout = 2000
}

animations {
    enabled = true
    bezier = liner, 1, 1, 0, 0
    animation = fadeIn, 1, 2, linear
    animation = fadeOut, 1, 2, linear
    animation = inputFieldDots, 1, 2, linear
    animation = inputFieldWidth, 1, 2, linear
    animation = inputFieldColors, 1, 2, linear
    animation = inputFieldFade, 1, 2, linear
}

background {
    monitor =
    path = $HOME/Repositories/arch-dotfiles/assets/wallpapers/default.png
    blur_passes = 0
    color = $base
}

input-field {
    monitor =
    size = 30%, 10%
    outline_thickness = 5

    dots_size = 0.4
    dots_spacing = 0.4
    dots_center = true
    dots_rounding = -1
    dots_text_format = 

    outer_color = $muave
    inner_color = $base
    font_color = $rosewater
    font_family = $font

    fade_on_empty = true
    fade_timeout = 4000
    placeholder_text = Password
    hide_input = false

    rounding = 0
    check_color = $muave
    fail_color = $red
    fail_text = Invalid
    capslock_color = $red
    numlock_color = $red
    bothlock_color = $red

    position = 0, 0
    halign = center
    valign = center
    zindex = 0
}

label {
    monitor =
    text = 󰌾
    text_align = center 
    color = $rosewater
    font_size = $font_size
    font_family = $font

    rotate = 0
    position = -5%, 5%
    halign = right
    valign = bottom
}
