#!/usr/bin/env bash
set -euo pipefail

# Set timezone
ln -sf /usr/share/zoneinfo/Asia/Singapore /etc/localtime
hwclock --systohc

# Set locale
sed -i 's/^#en_US\.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen
locale-gen
echo "LANG=en_US.UTF-8" > /etc/locale.conf
echo "KEYMAP=us" > /etc/vconsole.conf

# Set hostname
echo "arch" > /etc/hostname

# Set root password
echo "$1" | passwd root --stdin

# Create sudo user
useradd -m -G wheel -s /bin/bash rajdeep
echo "$1" | passwd rajdeep --stdin
sed -i 's/^# %wheel ALL=(ALL:ALL) ALL/%wheel ALL=(ALL:ALL) ALL/' /etc/sudoers

# Set parallel downloads
sed -i 's/^ParallelDownloads = [0-9]\+/ParallelDownloads = 20/' /etc/pacman.conf

# Enable color
sed -i 's/^#Color/Color/' /etc/pacman.conf

# Add candy
sed -i '/^ParallelDownloads = 20/a ILoveCandy' /etc/pacman.conf

# Enable multilib
sed -i "/\[multilib\]/,/Include/"'s/^#//' /etc/pacman.conf

# Install official packages
curl -fsSL https://raw.githubusercontent.com/rajdeepsh/arch-dotfiles/main/install/or-packages | pacman -Syu --noconfirm --needed -

# Setup greetd
mkdir -p /etc/greetd
cat > /etc/greetd/config.toml << 'EOF'
[terminal]
vt = "current"

[default_session]
command = "start-hyprland"
user = "rajdeep"

[initial_session]
command = "start-hyprland"
user = "rajdeep"
EOF

# Chromium policies
mkdir -p /etc/chromium/policies/managed
cat > /etc/chromium/policies/managed/color.json << 'EOF'
{"BrowserThemeColor": "#1e1e2e"}
EOF

# Install grub
grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=GRUB
sed -i 's/^GRUB_TIMEOUT_STYLE=.*/GRUB_TIMEOUT_STYLE=hidden/' /etc/default/grub
grub-mkconfig -o /boot/grub/grub.cfg

# Network
mkdir -p /etc/iwd
cat > /etc/iwd/main.conf << 'EOF'
[General]
EnableNetworkConfiguration=true
EOF

# Setup sshd
echo "PasswordAuthentication no" >>/etc/ssh/sshd_config.d/20-force_publickey_auth.conf
echo "AuthenticationMethods publickey" >>/etc/ssh/sshd_config.d/20-force_publickey_auth.conf

# NVIDIA specific
pacman -Syu --noconfirm --needed dkms linux-headers nvidia-open-dkms nvidia-utils lib32-nvidia-utils nvidia-settings egl-wayland
sed -i '/^MODULES=/c\MODULES=(nvidia nvidia_modeset nvidia_uvm nvidia_drm)' /etc/mkinitcpio.conf
sed -i '/^HOOKS=/s/kms//' /etc/mkinitcpio.conf
sed -i '/^HOOKS=/s/( /(/' /etc/mkinitcpio.conf
sed -i '/^HOOKS=/s/ )/)/' /etc/mkinitcpio.conf
sed -i '/^HOOKS=/s/  / /' /etc/mkinitcpio.conf
mkinitcpio -P

# Enable services
systemctl enable systemd-timesyncd.service
systemctl enable systemd-resolved.service
systemctl enable iwd.service
systemctl enable bluetooth.service
systemctl enable greetd.service