#!/usr/bin/env bash
set -euo pipefail

chmod 700 $HOME/.ssh
chmod 600 $HOME/.ssh/config
chmod 600 $HOME/.ssh/rajdeepsh
chmod 644 $HOME/.ssh/rajdeepsh.pub
wget -qO- https://github.com/rajdeepsh.keys >> $HOME/.ssh/authorized_keys

git config --global user.name "Rajdeep Singh Hundal"
git config --global user.email "rajd33psh@gmail.com"
git config --global gpg.format ssh
git config --global user.signingkey $HOME/.ssh/rajdeepsh.pub
git config --global commit.gpgsign true

systemctl --user enable --now ssh-agent.service

mkdir -p $HOME/Repositories
git -C $HOME/Repositories clone git@github.com:rajdeepsh/arch-dotfiles.git
cd $HOME/Repositories/arch-dotfiles/config
stow --adopt -t $HOME */
git reset --hard HEAD
cd $HOME

git -C $HOME clone https://aur.archlinux.org/paru.git
cd $HOME/paru
makepkg -si
cd $HOME
rm -rf $HOME/paru

paru -Syu --needed - < $HOME/Repositories/arch-dotfiles/install/aur-packages

echo
for i in {5..1}; do
  echo "Done! Restarting in ${i} seconds..."
  sleep 1
done
sudo reboot